base_url = "https://bfac.eloquentgeek.games"
title = "Bevy For the Aged and Confused"
description = "Practical game development with Bevy Engine that assumes you're slow and a little stupid."

build_search_index = true
compile_sass = true
default_language = "en"
generate_feeds = false
minify_html = true

taxonomies = [
  {name = "authors"},
]

[languages.eng]
taxonomies = [
  {name = "authors"},
]

[search]
include_title = true
include_description = false
include_content = true

[markdown]
# Theme can be customised by setting the `highlight_theme`
# variable to a theme supported by Zola
highlight_code = true

[extra]
author = "Rich 'Basie' Churcher"
docs_repo = "https://github.com/eloquentgeek/bfac"
edit_page = false
email = "basie@eloquentgeek.games"
ganalytics = ""  # Google Analytics code
github = "https://github.com/eloquentgeek"
is_netlify = false
language_code = "en-US"
navigation = true
repo_branch = "main"
theme_color = "#000"
timeformat = "%Y-%m-%d %H:%M:%S" # e.g. 2021-05-01 09:19:42
timezone = "UTC"
title_addition = "A practical guide to software development for the rather slow or stupid."
title_separator = "::"

## Math settings
# options: true, false. Enable math support globally,
# default: false. You can always enable math on a per page.
math = false
library = "katex"  # options: "katex", "mathjax". default is "katex".

## Open Graph
[extra.open]
enable = true
facebook_author = "eloquentgeekgames"
facebook_publisher = "eloquentgeekgames"
image = "static/images/stone.jpg"
og_locale = "en_US"

## JSON-LD
[extra.schema]
github = "https://github.com/eloquentgeek"
linked_in = "https://www.linkedin.com/in/richchurcher/"
logo = "static/images/stone.jpg"
site_links_search_box = false
twitter = "https://bsky.app/profile/eloquentgeek.bsky.social"
type = "Organization"

[[extra.menu.social]]
name = "Bluesky"
pre = '<svg aria-hidden="true" viewBox="0 0 64 57" width="20" style="width: 20px; height: 20px;"><path fill="#0085ff" d="M13.873 3.805C21.21 9.332 29.103 20.537 32 26.55v15.882c0-.338-.13.044-.41.867-1.512 4.456-7.418 21.847-20.923 7.944-7.111-7.32-3.819-14.64 9.125-16.85-7.405 1.264-15.73-.825-18.014-9.015C1.12 23.022 0 8.51 0 6.55 0-3.268 8.579-.182 13.873 3.805ZM50.127 3.805C42.79 9.332 34.897 20.537 32 26.55v15.882c0-.338.13.044.41.867 1.512 4.456 7.418 21.847 20.923 7.944 7.111-7.32 3.819-14.64-9.125-16.85 7.405 1.264 15.73-.825 18.014-9.015C62.88 23.022 64 8.51 64 6.55c0-9.818-8.578-6.732-13.873-2.745Z"></path></svg>'
url = "https://bsky.app/profile/eloquentgeek.bsky.social"
weight = 10

[[extra.menu.social]]
name = "GitHub"
pre = '<svg aria-hidden="true" viewBox="0 0 24 24" width="20" style="width: 20px; height: 20px;"><path d="M12.5.75C6.146.75 1 5.896 1 12.25c0 5.089 3.292 9.387 7.863 10.91.575.101.79-.244.79-.546 0-.273-.014-1.178-.014-2.142-2.889.532-3.636-.704-3.866-1.35-.13-.331-.69-1.352-1.18-1.625-.402-.216-.977-.748-.014-.762.906-.014 1.553.834 1.769 1.179 1.035 1.74 2.688 1.25 3.349.948.1-.747.402-1.25.733-1.538-2.559-.287-5.232-1.279-5.232-5.678 0-1.25.445-2.285 1.178-3.09-.115-.288-.517-1.467.115-3.048 0 0 .963-.302 3.163 1.179.92-.259 1.897-.388 2.875-.388.977 0 1.955.13 2.875.388 2.2-1.495 3.162-1.179 3.162-1.179.633 1.581.23 2.76.115 3.048.733.805 1.179 1.825 1.179 3.09 0 4.413-2.688 5.39-5.247 5.678.417.36.776 1.05.776 2.128 0 1.538-.014 2.774-.014 3.162 0 .302.216.662.79.547C20.709 21.637 24 17.324 24 12.25 24 5.896 18.854.75 12.5.75Z"></path></svg>'
url = "https://github.com/eloquentgeek/bfac"
weight = 20

[extra.footer]
info = 'Powered by <a href="https://www.getzola.org/">Zola</a>'

[[extra.footer.nav]]
name = "Eloquent Geek"
url = "https://eloquentgeek.games"
is_absolute_url = true
weight = 10
